{{ if .Values.robots.enabled -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "erddap.fullname" . }}-robots
  labels:
    {{- include "erddap.labels" . | nindent 4 }}
data:
  robots.txt: |-
    User-Agent: *
    Disallow: /erddap/files/
    Disallow: /files/
    Disallow: /images/
    Disallow: /*?
    Disallow: /*?*
    Disallow: /*.asc*
    Disallow: /*.csv*
    Disallow: /*.dods*
    Disallow: /*.esriAscii*
    Disallow: /*.esriCsv*
    Disallow: /*.geoJson*
    Disallow: /*.htmlTable*
    Disallow: /*.json*
    Disallow: /*.mat*
    Disallow: /*.nc*
    Disallow: /*.odvTxt*
    Disallow: /*.tsv*
    Disallow: /*.xhtml*
    Disallow: /*.geotif*
    Disallow: /*.itx*
    Disallow: /*.kml*
    Disallow: /*.pdf*
    Disallow: /*.png*
    Disallow: /*.large*
    Disallow: /*.small*
    Disallow: /*.transparentPng*
    Sitemap: /erddap/sitemap.xml
{{- end}}