apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "erddap.fullname" . }}-config
  labels:
    {{- include "erddap.labels" . | nindent 4 }}
data:
  config.sh: |-
    ERDDAP_bigParentDirectory="/erddapData/"
    ERDDAP_baseUrl="http://{{ .Values.domain.name }}"
    ERDDAP_baseHttpsUrl="https://{{ .Values.domain.name }}"
    ERDDAP_flagKeyKey="{{ .Values.flagKey.key }}"

    {{- if .Values.config.enabled }}
    {{ .Values.config.variables | nindent 4 }}
    {{- end}}

    {{- if .Values.emailConfig.enabled }}
    {{ .Values.emailConfig.variables | nindent 4 }}
    {{- end}}
