{{ if .Values.robots.enabled -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "erddap.fullname" . }}-robots
  labels:
    {{- include "erddap.labels" . | nindent 4 }}
data:
  setenv.sh: |-
{{ .Files.Get .Values.robots.file | indent 4 }}
{{- end}}